version: '3'

services:
  bot:
    env_file:
      - .env
    container_name: dark_bot_csharp
    restart: always
    network_mode: "host"
    build:
      context: .
      dockerfile: DockerFile
  bot_debug:
    image: mcr.microsoft.com/dotnet/sdk:6.0
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    environment:
      - DOTNET_WATCH_RESTART_ON_RUDE_EDIT=1
      - BOT_DEBUG=1
    container_name: dark_bot_csharp_debug
    restart: always
    network_mode: "host"
    command: "dotnet watch"
